### ISSUE TITLE
Tox organization disrespecting developers and users

### ISSUE THREAD

**Issue by suhr** [suhr/Tox-Discussions#1]
Continue of https://github.com/irungentoo/toxcore/issues/1495.
@Grayhatter masters the art of editing someone else's messages. Good job!

@olivia88: trigger anyone you want, I'm too lazy to do it.

**Comment by stal888** [comment]
@GrayHatter is such a meme

**Comment by ProMcTagonist** [comment]
The project is in dire need of someone capable of and willing to perform the roles that Proplex performed, namely:

* Being socially competent and communicating clearly and coherently

* Making developers be quiet and develop instead of antagonizing delicate situations

* Mediating between developers

* Addressing issues that arise in a professional manner and explaining what's going on to the community

* Knowing that editing comments and looking mad is the wrong thing to do and only hurts the project

* Understanding how to behave under the circumstances, which are that we are besiged by a smear campaign that will capitalize on every mistake made and preserve it forever, ready to display it in the worst possible light

* **Being on call 24/7/365 to do this forever**

Situation looks bleak.

**Comment by quininer** [comment]
Tox organizations need to be more open. Rust has a "This Week in Rust", Tox had a "Tox dev talk", but it stopped.
